export const sample_food = {
  name: "Bơ (quả)",
  calo: 160,
  carbs: 9,
  fat: 15,
  protein: 2,
  quantity: 100,
  totalFat: 15,
  saturatedFat: 2.1,
  transFat: 0,
  choles: 0,
  natri: 7,
  totalCarbohydrates: 9,
  dietaryFiber: 7,
  sugars: 0.7,
  kali: 485,
  vitaminA: 0,
  vitaminC: 10,
  canxi: 0,
  fe: 0,
};
const foodRecord = {
  foodNutrion: sample_food,
  weight: 200,
};
