// export const ListItemTypes = { MEAL, FOOD };

export const NutritionLabel = {
  calo: "Calories",
  carbs: "Carbs",
  fat: "Fat",
  protein: "Protein",
  quantity: "Khẩu phần",
  totalFat: "Tổng lượng chất béo",
  saturatedFat: "Chất béo bão hòa",
  transFat: "Chất béo chuyển hóa",
  cholesterol: "Cholesterol",
  natri: "Natri",
  totalCarbohydrates: "Tổng lượng carbohydrate",
  dietaryFiber: "Chất xơ",
  sugars: "Tổng lượng đường",
  kali: "Kali",
  vitaminA: "Vitamin A",
  vitaminC: "Vitamin C",
  canxi: "Canxi",
  fe: "Sắt",
};

export const NutritionUnit = {
  calo: "kcal",
  carbs: "g",
  fat: "g",
  protein: "g",
  // quantity: "Khẩu phần",
  totalFat: "g",
  saturatedFat: "g",
  transFat: "g",
  choles: "mg",
  natri: "mg",
  totalCarbohydrates: "g",
  dietaryFiber: "g",
  sugars: "g",
  kali: "mg",
  vitaminA: "mcg",
  vitaminC: "mg",
  canxi: "mg",
  fe: "mg",
}
